website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for, Response
from fpdf import FPDF
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_required, current_user
from .models import Note, Deals, TeamNotes, User
from . import db
import json
from sqlalchemy import delete
from datetime import *

views = Blueprint('views', __name__)

@views.route('/deals', methods=['GET', 'POST'])
def deals():
    if request.method == 'POST':
        DealID = request.form.get('dealid')
        DealName = request.form.get('dealName')
        ClientID = request.form.get('clientid')
        Comments = request.form.get('comments')
        DealStatus = request.form.get('dealstatus')
        Date = request.form.get('date')
        DateCreated = request.form.get('datecreated')

        new_deal = Deals(dealid = DealID, dealname = DealName, clientid = ClientID, comments = Comments, dealstatus = DealStatus, date = Date, datecreated = DateCreated)
        db.session.add(new_deal)
        db.session.commit()
        flash('Deal Added', category='success')

    our_deals=Deals.query.all()
    return render_template("deals.html", user=current_user, our_deals=our_deals)

@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    if request.method == 'POST':
        note = request.form.get('note')

        if len(note) < 1:
            flash('Note is too short!', category='error')
        else:
            new_note = Note(data=note, user_id=current_user.id)
            db.session.add(new_note)
            db.session.commit()
            flash('Note added!', category='success')


    ongoing_deals = Deals.query.filter_by(dealstatus = "Ongoing").all()

    return render_template("home.html", user=current_user, ongoing_deals=ongoing_deals)


@views.route('/delete-note', methods=['POST'])
def delete_note():
    note = json.loads(request.data)
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()

    return jsonify({})


@views.route('/view-deals')
def viewdeals():
    all_data = Deals.query.all()
    return render_template('view-deals.html', user=current_user, deals=all_data)

@views.route('/view-employees')
def viewemployees():
    User.query.filter_by(id=3).delete()
    all_data = User.query.all()
    return render_template('view-users.html', user=current_user, employees=all_data)

@views.route('/view-notes')
def viewnotes():
    all_data = Note.query.all()
    return render_template('view-notes.html', user=current_user, notes=all_data)

@views.route('/delete/<dealid>/', methods = ['GET', 'POST'])
def delete(dealid):
    my_data = Deals.query.get(dealid)
    db.session.delete(my_data)
    db.session.commit()
    flash("Deal Deleted Successfully")
    return redirect(url_for('views.adminviewdeals'))

@views.route('/admindelete/<id>/', methods = ['GET', 'POST'])
def deleteuser(id):
    my_user = User.query.get(id)
    db.session.delete(my_user)
    db.session.commit()
    flash("User Deleted Successfully")
    return redirect(url_for('views.viewemployees'))

@views.route('/update', methods=['GET', 'POST'])
def update():
    if request.method == 'POST':
        my_data = Deals.query.get(request.form.get('dealid'))
        my_data.dealname = request.form['dealname']
        my_data.clientid = request.form['clientid']
        my_data.comments = request.form['comments']
        my_data.dealstatus = request.form.get('dealstatus')
        my_data.date = request.form['date']

        db.session.commit()
        flash("Deal Updated Successfully")
        return redirect(url_for('views.viewdeals'))

@views.route('/admin-home', methods=['GET', 'POST'])
def adminhome():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            flash('Account created!', category='success')
            return redirect(url_for('views.viewemployees'))
    return render_template("adminhome.html", user=current_user)

@views.route('/download/alldealsreport/pdf')
def download_all_deals_report():
    result = Deals.query.all()
    pdf = FPDF()
    pdf.add_page()

    page_width = pdf.w - 2 * pdf.l_margin

    pdf.set_font('Times', 'B', 14.0)
    pdf.cell(page_width, 0.0, 'All Deals', align='C')
    pdf.ln(10)
    col_width = page_width / 7

    pdf.set_font('Times', 'B', 12)
    th = 15
    pdf.cell(col_width, th, 'Deal ID', border=1)
    pdf.cell(col_width, th, 'Deal Name', border=1)
    pdf.cell(col_width, th, 'Client ID', border=1)
    pdf.cell(col_width, th, 'Comments', border=1)
    pdf.cell(col_width, th, 'Deal Status', border=1)
    pdf.cell(col_width, th, 'Date Initiated', border=1)
    pdf.cell(col_width, th, 'Date Updated', border=1)
    pdf.ln(th)

    pdf.set_font('Times', '', 12)

    for row in result:
        pdf.cell(col_width, th, row.dealid, border=1)
        pdf.cell(col_width, th, row.dealname, border=1)
        pdf.cell(col_width, th, row.clientid, border=1)
        pdf.cell(col_width, th, row.comments, border=1)
        pdf.cell(col_width, th, row.dealstatus, border=1)
        pdf.cell(col_width, th, row.datecreated, border=1)
        pdf.cell(col_width, th, row.date, border=1)
        pdf.ln(th)

    pdf.ln(10)

    pdf.set_font('Times', '', 10.0)
    pdf.cell(page_width, 0.0, '- end of report -', align='C')

    return Response(pdf.output(dest='S').encode('latin-1'), mimetype='application/pdf',
                    headers={'Content-Disposition': 'attachment;filename=All Deals Report.pdf'})

@views.route('/download/ongoingdealsreport/pdf')
def download_ongoing_deals_report():
    result = Deals.query.filter_by(dealstatus = 'Ongoing').all()
    pdf = FPDF()
    pdf.add_page()

    page_width = pdf.w - 2 * pdf.l_margin

    pdf.set_font('Times', 'B', 14.0)
    pdf.cell(page_width, 0.0, 'Ongoing Deals', align='C')
    pdf.ln(10)
    col_width = page_width / 6

    pdf.set_font('Times', 'B', 12)
    th = 15
    pdf.cell(col_width, th, 'Deal ID', border=1)
    pdf.cell(col_width, th, 'Client ID', border=1)
    pdf.cell(col_width, th, 'Comments', border=1)
    pdf.cell(col_width, th, 'Deal Status', border=1)
    pdf.cell(col_width, th, 'Date', border=1)
    pdf.ln(th)

    pdf.set_font('Times', '', 12)

    for row in result:
        pdf.cell(col_width, th, row.dealid, border=1)
        pdf.cell(col_width, th, row.dealname, border=1)
        pdf.cell(col_width, th, row.clientid, border=1)
        pdf.cell(col_width, th, row.comments, border=1)
        pdf.cell(col_width, th, row.dealstatus, border=1)
        pdf.cell(col_width, th, row.date, border=1)
        pdf.ln(th)

    pdf.ln(10)

    pdf.set_font('Times', '', 10.0)
    pdf.cell(page_width, 0.0, '- end of report -', align='C')

    return Response(pdf.output(dest='S').encode('latin-1'), mimetype='application/pdf',
                    headers={'Content-Disposition': 'attachment;filename=Ongoing Deal Report.pdf'})

@views.route('/download/closeddealsreport/pdf')
def download_closed_deals_report():
    result = Deals.query.filter_by(dealstatus = 'Closed').all()
    pdf = FPDF()
    pdf.add_page()

    page_width = pdf.w - 2 * pdf.l_margin

    pdf.set_font('Times', 'B', 14.0)
    pdf.cell(page_width, 0.0, 'Closed Deals', align='C')
    pdf.ln(10)
    col_width = page_width / 6

    pdf.set_font('Times', 'B', 12)
    th = 15
    pdf.cell(col_width, th, 'Deal ID', border=1)
    pdf.cell(col_width, th, 'Deal Name', border=1)
    pdf.cell(col_width, th, 'Client ID', border=1)
    pdf.cell(col_width, th, 'Comments', border=1)
    pdf.cell(col_width, th, 'Deal Status', border=1)
    pdf.cell(col_width, th, 'Date', border=1)
    pdf.ln(th)

    pdf.set_font('Times', '', 12)

    for row in result:
        pdf.cell(col_width, th, row.dealid, border=1)
        pdf.cell(col_width, th, row.dealname, border=1)
        pdf.cell(col_width, th, row.clientid, border=1)
        pdf.cell(col_width, th, row.comments, border=1)
        pdf.cell(col_width, th, row.dealstatus, border=1)
        pdf.cell(col_width, th, row.date, border=1)
        pdf.ln(th)

    pdf.ln(10)

    pdf.set_font('Times', '', 10.0)
    pdf.cell(page_width, 0.0, '- end of report -', align='C')

    return Response(pdf.output(dest='S').encode('latin-1'), mimetype='application/pdf',
                    headers={'Content-Disposition': 'attachment;filename=Closed Deals Report.pdf'})


@views.route('/dealinterface/<dealid>/', methods=['GET', 'POST'])
def deal_progress(dealid):
    if request.method == 'POST':
        Name = request.form.get('name')
        Update = request.form.get('update')
        new_update = TeamNotes(name=current_user.first_name, update=Update, deal_id=dealid)
        db.session.add(new_update)
        db.session.commit()
        flash('Note added!', category='success')

    all_notes = TeamNotes.query.filter_by(deal_id=dealid).all()

    return render_template("dealinterface.html", user=current_user, all_notes=all_notes)

website/templates/admin-dealinterface.html
{% extends "base.html" %} {% include "admin_nav.html" %}
{% block content %}
<head>
<style>
  .centerAlign{
  margin: auto;
  width: 50%;
  text-align: center;
  padding: 10px;
  }
</style>
</head>
<br><br><br>
<h3 align="center">Formal Team Updates on Deal Progress:</h3><br>
<ul class="list-group list-group-flush" id="notes"></ul>
  {% for note in all_notes %}
  <li class="list-group-item">
    <strong>{{ note.name }}:</strong>
      {{ note.update }}
      <a href="/admin-deletenote/{{note.id}}" class="btn btn-danger btn-xs" onclick="return confirm('Are You Sure To Delete ?')" style="margin-left:94%;">Delete</a><br><br>
    {% endfor %}
{% endblock %}
  </li>

website/templates/admin-viewdeals.html
{% extends 'base.html' %} {% include "admin_nav.html" %}

{% block title %} View Deals {% endblock %}

{% block content %}
<head>
    <style>
        .space {
        width: 10px;
        height: auto;
        display: inline-block;
        }
    </style>
</head>
<br>
<h2>Manage Deals</h2>
<br>
<div class="norm-container">
    <div class="row">
        <div class="col md-12">
            <div class="jumbotron p-3">
                <table class="table table-hover table-striped">
                    <tr>
                        <th>Deal ID</th>
                        <th>Deal Name</th>
                        <th>Client ID</th>
                        <th>Comments</th>
                        <th>Deal Status</th>
                        <th>Date of Initiation</th>
                        <th>Date Last Updated</th>
                    </tr>
                   {% for row in deals %}
                    <tr>
                        <td style="text-align:center">{{row.dealid}}</td>
                        <td style="text-align:center">{{row.dealname}}</td>
                        <td style="text-align:center">{{row.clientid}}</td>
                        <td style="text-align:center">{{row.comments}}</td>
                        <td style="text-align:center">{{row.dealstatus}}</td>
                        <td style="text-align:center">{{row.datecreated}}</td>
                        <td style="text-align:center">{{row.date}}</td>
                        <td style="text-align:center">
                            <a href="/update/{{row.dealid}}" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#modaledit{{row.dealid}}">Edit</a><br><br>
                            <a href="/delete/{{row.dealid}}" class="btn btn-danger btn-xs" onclick="return confirm('Are You Sure To Delete ?')">Delete</a><br><br>
                            <a href="/admin-dealinterface/{{row.dealid}}" class="btn btn-primary" style="width: 130;">Open Deal Interface</a>
                        </td>
                    </tr>

     <div id="modaledit{{row.dealid}}" class="modal fade" role="dialog">
        <div class="modal-dialog">
        <div class="modal-content">
       <div class="modal-header"><h4 class="modal-title">Update Information</h4></div>
        <div class="modal-body">
        <form action="{{url_for('views.update')}}" method="POST">
         <div class="form-group">
          <label>Deal Name:</label>
          <input type="hidden"  name="dealid" value="{{row.dealid}}">
          <input type="text" class="form-control" name="dealname" value="{{row.dealname}}">
         </div>
         <div class="form-group">
          <label>Client ID:</label>
          <input type="text" class="form-control" name="clientid" value="{{row.clientid}}">
         </div>
         <div class="form-group">
          <label>Comments:</label>
          <input type="text" class="form-control" name="comments" value="{{row.comments}}">
         </div>
         <div class="form-group">
          <label>Deal Status:</label>
             <select id="dealstatus" name="dealstatus" style="width:465px; margin-left: auto; margin-right: auto;">
                 {% if row.dealstatus =="Ongoing" %}
                    <option value="Ongoing" selected="selected">Ongoing</option>
                    <option value="Cold">Cold</option>
                    <option value="Closed">Closed</option>
                 {% elif row.dealstatus =="Cold" %}
                    <option value="Ongoing">Ongoing</option>
                    <option value="Cold" selected="selected">Cold</option>
                    <option value="Closed">Closed</option>
                 {% else %}
                    <option value="Ongoing">Ongoing</option>
                    <option value="Cold">Cold</option>
                    <option value="Closed" selected="selected">Closed</option>
                 {% endif %}
            </select>
         </div>
         <div class="form-group">
          <label>Date Last Updated:</label>
          <input type="date" class="form-control" name="date" value="{{row.date}}">
         </div>
         <div class="form-group">
          <button class="btn btn-primary" type="submit">Update</button>
         </div>
        </form>
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
      </div>
     </div>
     {% endfor %}
    </table>
   </div>
 </div>
 </div>
    <a href="{{ url_for('views.download_all_deals_report') }}"><button type="button" class="btn btn-primary btn-inline">Generate PDF Report of All Deals</button></a>
    <div class="space"></div>
    <a href="{{ url_for('views.download_ongoing_deals_report') }}"><button type="button" class="btn btn-primary btn-inline">Generate PDF Report of Ongoing Deals</button></a>
    <div class="space"></div>
    <a href="{{ url_for('views.download_closed_deals_report') }}"><button type="button" class="btn btn-primary btn-inline">Generate PDF Report of Closed Deals</button></a><br><br>

{% endblock %}

website/templates/admin_nav.html
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href=
"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity=
"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
        crossorigin="anonymous" />
    <link rel="stylesheet" href=
"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />

    <link rel="stylesheet" href=
"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />


  </head>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="#">
            <img src= "https://winpeforum.com/assets/elements/Arpwood_250x250.png"
                 width="80" height="100" alt="" />
        </a>
    </div>


    <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbar"
    >
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
            <a class="nav-item nav-link" id="home" href="/admin-home">Add Employees</a>
            <a class="nav-item nav-link" id="employeelogin" href="/view-employees">View Employees</a>
            <a class="nav-item nav-link" id="viewnotes" href="/view-notes">View Notes</a>
            <a class="nav-item nav-link" id="adminviewdeals" href="/admin-viewdeals">View Deals</a>
            <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
        </div>
    </div>
</nav>

website/templates/adminhome.html
{% extends "base.html" %} {% include "admin_nav.html" %} {% block title %}Sign Up{% endblock %} {% block
content %}
<head>
<style>
  .centerAlign{
  margin: auto;
  width: 10%;
  text-align: center;
  padding: 10px;
  }

</style>
</head>
<br><br>
<form method="POST">
  <h3 align="center">Enter Employee as User</h3>
  <div class="form-group">
    <div class="centerAlign"> Email </div>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      style="width: 300px; margin: auto;"
    />
  </div>
  <div class="form-group">
    <div class="centerAlign">First Name</div>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      style="width: 300px; margin: auto;"
    />
  </div>
  <div class="form-group">
    <div class="centerAlign">Last Name</div>
    <input
      type="text"
      class="form-control"
      id="lastName"
      name="lastName"
      style="width: 300px; margin: auto;"
    />
  </div>
  <div class="form-group">
    <div class="centerAlign">Password</div>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      style="width: 300px; margin: auto;"
    />
  </div>
  <div class="form-group">
    <div class="centerAlign">Confirm</div>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      style="width: 300px; margin: auto;"
    />
  <div class="form-group">
  <br />
  <button type="submit" class="btn btn-login" style="margin-left:auto;margin-right:auto;display:block">Submit</button>
</form>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href=
"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity=
"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
        crossorigin="anonymous" />
    <link rel="stylesheet" href=
"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />

    <link rel="stylesheet" href=
"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">


    <title>{% block title %}Home{% endblock %}</title>

  </head>
  <body>
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="norm-container">{% block content %} {% endblock %}</div>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
  </body>
</html>

website/templates/dealinterface.html
{% extends "base.html" %} {% include "nav.html" %}
{% block content %}
<head>
<style>
  .centerAlign{
  margin: auto;
  width: 50%;
  text-align: center;
  padding: 10px;
  }
</style>
</head>
<br><br><br>

  <form method="POST">
    <br><br>
    <h3 align="center">Team Progress Tracker (Notes):</h3><br>
    <div class="form-group">
    </div>
      <div class="centerAlign">Your Progress Update:</div>
      <input
        type="text"
        class="form-control"
        id="update"
        name="update"
        style="width: 400px; height: 80px; margin: auto;"
      /><br><br>
    <button type="submit" class="btn btn-login" style="margin-left:auto;margin-right:auto;display:block">Submit</button>
  <br>
  </form>

  <br><br>
  <h3 align="center">Formal Team Updates on Deal Progress:</h3><br>
  <ul class="list-group list-group-flush" id="notes">
    {% for note in all_notes %}
    <li class="list-group-item">
      <strong>{{ note.name }}:</strong>
      {% if note.name == current_user.first_name %}
        {{ note.update }}
        <a href="/deletenote/{{note.id}}" class="btn btn-danger btn-xs" onclick="return confirm('Are You Sure To Delete ?')" style="margin-left:95%;">Delete</a><br><br>
      {% else %}
        {{ note.update }}<br><br><br>
      {% endif %}
      {% endfor %}
  {% endblock %}

website/templates/login.html
{% extends "base.html" %} {% include "nav.html" %} {% block title %}Login{% endblock %} {% block content
%}
<head>
<style>
  .centerAlign{
  margin: auto;
  width: 10%;
  text-align: center;
  padding: 10px;
  }
</style>
</head>


  <form method="POST">
    <br><br><br><br>
    <br><br><br><br>
    <h3 align="center">Login</h3>
    <div class="form-group">
      <div class="centerAlign">Email</div>
      <input
        type="email"
        class="form-control"
        id="email"
        name="email"
        style="width: 300px; margin: auto;"
      />
    </div>
    <div class="form-group">
      <div class="centerAlign">Password</div>
      <input
        type="password"
        class="form-control"
        id="password"
        name="password"
        style="width: 300px; margin: auto;"
      />
    </div>
    <br />
    <button type="submit" class="btn btn-login" style="margin-left:auto;margin-right:auto;display:block">Login</button>
    <br><br><br><br><br><br><br><br><br>
  </form>
</div>
{% endblock %}

website/templates/view-deals.html
{% extends 'base.html' %} {% include "nav.html" %}

{% block title %} View Deals {% endblock %}

{% block content %}
<head>
    <style>
        .space {
        width: 10px;
        height: auto;
        display: inline-block;
        }
    </style>
</head>
<br>
<h2>Manage Deals</h2>
<br>
<div class="norm-container">
    <div class="row">
        <div class="col md-12">
            <div class="jumbotron p-3">
                <table class="table table-hover table-striped">
                    <tr>
                        <th>Deal ID</th>
                        <th>Deal Name</th>
                        <th>Client Name</th>
                        <th>Comments</th>
                        <th>Deal Status</th>
                        <th>Date of Initiation</th>
                        <th>Date Last Updated</th>
                    </tr>
                   {% for row in deals %}
                    <tr>
                        <td style="text-align:center">{{row.dealid}}</td>
                        <td style="text-align:center">{{row.dealname}}</td>
                        <td style="text-align:center">{{row.clientid}}</td>
                        <td style="text-align:center">{{row.comments}}</td>
                        <td style="text-align:center">{{row.dealstatus}}</td>
                        <td style="text-align:center">{{row.datecreated}}</td>
                        <td style="text-align:center">{{row.date}}</td>
                        <td style="text-align:center">
                            <a href="/update/{{row.dealid}}" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#modaledit{{row.dealid}}">Edit</a><br><br>
                            <a href="/dealinterface/{{row.dealid}}" class="btn btn-primary" style="width: 130;">Open Deal Interface</a>
                        </td>
                    </tr>

     <div id="modaledit{{row.dealid}}" class="modal fade" role="dialog">
        <div class="modal-dialog">
        <div class="modal-content">
       <div class="modal-header"><h4 class="modal-title">Update Information</h4></div>
        <div class="modal-body">
        <form action="{{url_for('views.update')}}" method="POST">
         <div class="form-group">
          <label>Deal Name:</label>
          <input type="hidden"  name="dealid" value="{{row.dealid}}">
          <input type="text" class="form-control" name="dealname" value="{{row.dealname}}">
         </div>
         <div class="form-group">
          <label>Client Name:</label>
          <input type="text" class="form-control" name="clientid" value="{{row.clientid}}">
         </div>
         <div class="form-group">
          <label>Comments:</label>
          <input type="text" class="form-control" name="comments" value="{{row.comments}}">
         </div>
         <div class="form-group">
          <label>Deal Status:</label>
             <select id="dealstatus" name="dealstatus" style="width:465px; margin-left: auto; margin-right: auto;">
                 {% if row.dealstatus =="Ongoing" %}
                    <option value="Ongoing" selected="selected">Ongoing</option>
                    <option value="Cold">Cold</option>
                    <option value="Closed">Closed</option>
                 {% elif row.dealstatus =="Cold" %}
                    <option value="Ongoing">Ongoing</option>
                    <option value="Cold" selected="selected">Cold</option>
                    <option value="Closed">Closed</option>
                 {% else %}
                    <option value="Ongoing">Ongoing</option>
                    <option value="Cold">Cold</option>
                    <option value="Closed" selected="selected">Closed</option>
                 {% endif %}
            </select>
         </div>
         <div class="form-group">
          <label>Date Last Updated:</label>
          <input type="date" class="form-control" name="date" value="{{row.date}}">
         </div>
         <div class="form-group">
          <button class="btn btn-primary" type="submit">Update</button>
         </div>
        </form>
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
      </div>
     </div>
     {% endfor %}
    </table>
   </div>
 </div>
 </div>
    <a href="{{ url_for('views.download_all_deals_report') }}"><button type="button" class="btn btn-primary btn-inline">Generate PDF Report of All Deals</button></a>
    <div class="space"></div>
    <a href="{{ url_for('views.download_ongoing_deals_report') }}"><button type="button" class="btn btn-primary btn-inline">Generate PDF Report of Ongoing Deals</button></a>
    <div class="space"></div>
    <a href="{{ url_for('views.download_closed_deals_report') }}"><button type="button" class="btn btn-primary btn-inline">Generate PDF Report of Closed Deals</button></a><br><br>

{% endblock %}